// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/dbsheet/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from wire.go:

func injectStringer(s MyString) fmt.Stringer {
	return s
}
